version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
          name: config
          command: meson -Dbuild_docs=true . build
      - run:
          name: build
          command: ninja -C build
